export const genreColor = [
  {id: 28, color: 'darkgrey'},
  {id: 12, color: 'maroon'},
  {id: 16, color: 'hotpink'},
  {id: 35, color: 'darkviolet'},
  {id: 80, color: 'darkblue'},
  {id: 99, color: 'gold'},
  {id: 18, color: 'darkturquoise'},
  {id: 10751, color: 'coral'},
  {id: 14, color: 'blue'},
  {id: 36, color: 'darkgreen'},
  {id: 27, color: 'red'},
  {id: 10402, color: 'mediumorchid'},
  {id: 9648, color: 'indianred'},
  {id: 10749, color: 'pink'},
  {id: 878, color: 'rosybrown'},
  {id: 10770, color: 'steelblue'},
  {id: 53, color: 'cornflowerblue'},
  {id: 10752, color: 'olive'},
  {id: 37, color: 'indigo'},
]
